---
title: 'Problem 5'
author: "Radosław Majkut"
date: "2023-09-29"
output:  pdf_document
---

### Problem

Let

$$x = .123456789101112 .. .998999,$$
where the digits are obtained by writing the integers 1 through 999 in order. Find the 1983rd digit to the right of the decimal point

### Solution

There are:

* 9 single-digit integers, from 1 to 9, for the total of $9$ digits
* 90 double-digit integers, from 10 to 99, for the total of $2 \cdot 90 = 180$ digits
* 900 triple-digit integers, from 100 to 999, for the total of $3 \cdot 900 = 2700$ digits

Since 1983 is greater than $180 + 9$ we can subtract them to get how many digits remain. This is $1983 - 180 - 9 = 1794$. To get the index of the triple-digit integer which will contain the 1983rd digit in the string, we do floor division by 3 which works out to be 598. That 598th triple-digit integer is 697 (because the first one is 100). But which digit is at the 1983rd position? We notice that because $1794 \mod 3 = 0$ (1794 divides without remainder by 3) we can conclude that the last digit, 7, is the answer (if the remainder was 1, the digit 6 would be the answer and if the remainder was 2, the digit 9 would be the answer).